// Real brand favicons, hosted as static files under public/logos/ and served from
// Juniper's own origin (issue #249: this used to be ~170KB of base64 data URIs
// embedded directly in this module, which put the whole set in the main JS bundle
// whether or not a page ever rendered one). Extracted verbatim, byte for byte, from
// the prior inline data URIs; nothing about the images themselves changed.
export const LOGOS: Record<string, string> = {
  adobe: '/logos/adobe.png',
  ally: '/logos/ally.png',
  amazon: '/logos/amazon.png',
  amex: '/logos/amex.png',
  apple: '/logos/apple.png',
  betterment: '/logos/betterment.png',
  capitalone: '/logos/capitalone.png',
  chase: '/logos/chase.png',
  chevron: '/logos/chevron.png',
  earnest: '/logos/earnest.png',
  fidelity: '/logos/fidelity.png',
  marcus: '/logos/marcus.png',
  netflix: '/logos/netflix.png',
  nyt: '/logos/nyt.png',
  openai: '/logos/openai.png',
  planetfitness: '/logos/planetfitness.png',
  policygenius: '/logos/policygenius.png',
  shell: '/logos/shell.png',
  sofi: '/logos/sofi.png',
  spotify: '/logos/spotify.png',
  target: '/logos/target.png',
  toyota: '/logos/toyota.png',
  traderjoes: '/logos/traderjoes.png',
  trustwill: '/logos/trustwill.png',
  vanguard: '/logos/vanguard.png',
  wealthfront: '/logos/wealthfront.png',
  wholefoods: '/logos/wholefoods.png',
  bankofamerica: '/logos/bankofamerica.png',
  wellsfargo: '/logos/wellsfargo.png',
  citi: '/logos/citi.png',
  usbank: '/logos/usbank.png',
  pnc: '/logos/pnc.png',
  chime: '/logos/chime.png',
  truist: '/logos/truist.png',
  schwab: '/logos/schwab.png',
  robinhood: '/logos/robinhood.png',
  etrade: '/logos/etrade.png',
  merrill: '/logos/merrill.png',
  empower: '/logos/empower.png',
  tiaa: '/logos/tiaa.png',
  discover: '/logos/discover.png',
  salliemae: '/logos/salliemae.png',
  nelnet: '/logos/nelnet.png',
  mohela: '/logos/mohela.png',
  rocketmortgage: '/logos/rocketmortgage.png',
  paypal: '/logos/paypal.png',
  venmo: '/logos/venmo.png',
  cashapp: '/logos/cashapp.png',
};
