-- Stage: waitlist table for early-access sign-ups from the public landing page.
-- Anonymous visitors INSERT through /api/waitlist (using the anon key). The
-- table is write-only via the Data API — no SELECT/UPDATE/DELETE is granted, so
-- sign-ups can't be read back through PostgREST. Admins read it in the Supabase
-- dashboard or via the service role. Idempotent — safe to re-run.

-- ── Table ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.waitlist (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email          TEXT NOT NULL,
  journey_stage  TEXT,
  source         TEXT,
  status         TEXT NOT NULL DEFAULT 'new',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- One row per email (case-insensitive). Lets the endpoint treat repeat
-- sign-ups as idempotent instead of accumulating duplicates.
CREATE UNIQUE INDEX IF NOT EXISTS waitlist_email_unique
  ON public.waitlist (lower(email));

-- ── Grants ────────────────────────────────────────────────────────────────
-- Tables created via raw SQL don't auto-grant Data API access. Grant INSERT
-- only (no SELECT/UPDATE/DELETE) to anon + authenticated so the public form can
-- write but nobody can read the list through the API.
GRANT INSERT ON public.waitlist TO anon, authenticated;

-- ── RLS ───────────────────────────────────────────────────────────────────
ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS waitlist_insert_anyone ON public.waitlist;
CREATE POLICY waitlist_insert_anyone
  ON public.waitlist
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- No SELECT/UPDATE/DELETE policies on purpose: with RLS enabled and no read
-- policy, PostgREST cannot return rows even with the anon/authenticated role.
